# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c65609104a4e62cdee9a774d4999788e803b78ce6902290aff01ea735a350c4a1ff37168628c0699defd3d1c5e387d8528dc16e66af1afd3862e1c492f26f307

test:
  secret_key_base: fd350cfd5d1592a1b166da1e832157a4ff24a2a8e98e74a1e529a3a997d4f2901331fad52ceeea9db9857a8863bccde1b471fca69e0b582ad731dc980f10758a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
